UserManagement.MVC/Models/ErrorViewModel.cs
namespace UserManagement.MVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

UserManagement.MVC/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;
using AutoMapper;
using UserManagement.Application.Common.Mappings;
using UserManagement.Application.Queries.User.Login;

namespace UserManagement.MVC.Models;

public class LoginViewModel : IMapWith<LoginUserQuery>
{
    [Required]
    [EmailAddress(ErrorMessage = "Is not an e-mail")]
    public string Email { get; set; }
    
    [Required]
    public string Password { get; set; }

    public void Mapping(Profile profile)
    {
        profile.CreateMap<LoginViewModel, LoginUserQuery>()
            .ForMember(d => d.Email,
                opt => opt.MapFrom(s => s.Email))
            .ForMember(d => d.Password,
                opt => opt.MapFrom(s => s.Password));
    }
}

UserManagement.MVC/Models/RegistrationViewModel.cs
using System.ComponentModel.DataAnnotations;
using AutoMapper;
using UserManagement.Application.Commands.User.Registration;
using UserManagement.Application.Common.Mappings;

namespace UserManagement.MVC.Models;

public class RegistrationViewModel : IMapWith<CreateUserCommand>
{
    [Required] 
    public string Name { get; set; }
    
    [Required]
    [EmailAddress(ErrorMessage = "Is not an e-mail")]
    public string Email { get; set; }

    [Required] 
    public string Password { get; set; }
    
    [Required]
    [Compare("Password", ErrorMessage = "Password don't match")]
    public string PasswordConfirm { get; set; }

    public void Mapping(Profile profile)
    {
        profile.CreateMap<RegistrationViewModel, CreateUserCommand>()
            .ForMember(d => d.Name,
                opt => opt.MapFrom(s => s.Name))
            .ForMember(d => d.Email,
                opt => opt.MapFrom(s => s.Email))
            .ForMember(d => d.Password,
                opt => opt.MapFrom(s => s.Password));
    }
}

UserManagement.MVC/Controllers/AdminPanelController.cs
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using UserManagement.Application.Commands.User.Blocking;
using UserManagement.Application.Commands.User.Removing;
using UserManagement.Application.Commands.User.Unblocking;
using UserManagement.Application.Queries.User.GetListUsers;
using UserManagement.Domain;
using UserManagement.MVC.FilterAttributes;

namespace UserManagement.MVC.Controllers;

[ServiceFilter(typeof(UserActionsFilter))]
[Authorize]
public class AdminPanelController : BaseController
{
    private readonly IMediator _mediator;
    private readonly SignInManager<User> _signInManager;

    public AdminPanelController(IMediator mediator,
        SignInManager<User> signInManager)
    {
        _mediator = mediator;
        _signInManager = signInManager;
    }
    
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var query = new GetListUsersQuery();
        var users = await _mediator.Send(query);
        
        return View(users);
    }

    [HttpPost]
    public async Task<IActionResult> Remove([FromBody] long[] selectedUsers)
    {
        var command = new RemoveUserCommand
        {
            SelectedUsers = selectedUsers,
            CurrentUserId = UserId
        };
        await _mediator.Send(command);
        return RedirectToAction("Index", "AdminPanel");
    }
    
    [HttpPost]
    public async Task<IActionResult> Block([FromBody] long[] selectedUsers)
    {
        var command = new BlockUserCommand
        {
            CurrentUserId = UserId,
            SelectedUsers = selectedUsers
        };
        await _mediator.Send(command);
        return RedirectToAction("Index", "AdminPanel");
    }
    
    [HttpPost]
    public async Task<IActionResult> Unblock([FromBody] long[] selectedUsers)
    {
        var command = new UnblockUserCommand { SelectedUsers = selectedUsers };
        await _mediator.Send(command);
        return RedirectToAction("Index");
    }
    
    [HttpGet]
    public async Task<IActionResult> SignOut()
    {
        await _signInManager.SignOutAsync();
        
        return RedirectToAction("Index", "Login");
    }
}

UserManagement.MVC/Controllers/BaseController.cs
using System.Security.Claims;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace UserManagement.MVC.Controllers;

public class BaseController : Controller
{
    private IMediator? _mediator;

    protected IMediator Mediator =>
        _mediator ?? HttpContext.RequestServices.GetService<IMediator>()!;

    internal long? UserId => User.Identity!.IsAuthenticated
        ? Convert.ToInt64(User.FindFirst(ClaimTypes.NameIdentifier)?.Value)
        : null;
}

UserManagement.MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using UserManagement.MVC.Models;

namespace UserManagement.MVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

UserManagement.MVC/Controllers/LoginController.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using UserManagement.Application.Queries.User.Login;
using UserManagement.MVC.Models;

namespace UserManagement.MVC.Controllers;

public class LoginController : BaseController
{
    private readonly IMapper _mapper;
    private readonly IMediator _mediator;

    public LoginController(IMapper mapper, IMediator mediator)
    {
        _mapper = mapper;
        _mediator = mediator;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Index(LoginViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        var query = _mapper.Map<LoginUserQuery>(model);
        query.State = ModelState;
        var state = await _mediator.Send(query);
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        return RedirectToAction("Index", "AdminPanel");
    }
}

UserManagement.MVC/Controllers/RegistrationController.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using UserManagement.Application.Commands.User.Registration;
using UserManagement.MVC.Models;

namespace UserManagement.MVC.Controllers;

public class RegistrationController : BaseController
{
    private readonly IMapper _mapper;
    private readonly IMediator _mediator;

    public RegistrationController(IMapper mapper, IMediator mediator)
    {
        _mapper = mapper;
        _mediator = mediator;
    }
    
    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> Index(RegistrationViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        var command = _mapper.Map<CreateUserCommand>(model);
        var userCreation = await _mediator.Send(command);
        if (userCreation == false)
        {
            ModelState.AddModelError("UserExists", "The entered email is already exists");
            return View(model);
        }
        return RedirectToAction("Index", "AdminPanel");
    }
}

UserManagement.MVC/Views/AdminPanel/Index.cshtml
@model UserManagement.Application.Queries.User.GetListUsers.UsersVm

@{
    ViewData["Title"] = "Admin panel";
}

<div class="container mt-5 px-2">

    <div class="mb-2 d-flex justify-content-between align-items-center">
        <div class="flex-container">
             <div>
                 <button id="block-btn" class="btn btn-outline-info flex-item">
                     <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-lock-fill" viewBox="0 0 16 16">
                         <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2z"/>
                     </svg>
                 </button>
             </div>
            <div>
                <button id="unblock-btn" class="btn btn-outline-info flex-item">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-hammer" viewBox="0 0 16 16">
                        <path d="M9.972 2.508a.5.5 0 0 0-.16-.556l-.178-.129a5.009 5.009 0 0 0-2.076-.783C6.215.862 4.504 1.229 2.84 3.133H1.786a.5.5 0 0 0-.354.147L.146 4.567a.5.5 0 0 0 0 .706l2.571 2.579a.5.5 0 0 0 .708 0l1.286-1.29a.5.5 0 0 0 .146-.353V5.57l8.387 8.873A.5.5 0 0 0 14 14.5l1.5-1.5a.5.5 0 0 0 .017-.689l-9.129-8.63c.747-.456 1.772-.839 3.112-.839a.5.5 0 0 0 .472-.334z"/>
                    </svg>
                </button>
            </div>
            <div>
                <button id="delete-btn" class="btn btn-outline-info flex-item">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                        <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
                    </svg>
                </button>
            </div>
            
        </div>
    </div>
    
    <div>
        <table class="table">
            <thead class="table-dark">
            <tr>
                <th scope="col" width="10%">
                    <input id="all-checks" type="checkbox">
                </th>
                <th scope="col" width="10%">Id</th>
                <th scope="col" width="10%">Email</th>
                <th scope="col" width="10%">UserName</th>
                <th scope="col" width="10%">Registration date</th>
                <th scope="col" width="10%">Last login date</th>
                <th scope="col" width="10%">Status</th>
            </tr>
            </thead>
            <tbody class="table-group-divider">
            @foreach (var user in Model.Users.OrderBy(u => u.Id))
            {
                <tr>
                    <th scope="row">
                        <input class="chboxes" value="@user.Id" type="checkbox">
                    </th>
                    <td>@user.Id</td>
                    <td>@user.Email</td>
                    <td>@user.UserName</td>
                    <td>@user.RegistrationTime</td>
                    <td>@user.LastLoginTime</td>
                    <td>@user.Status</td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

UserManagement.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

UserManagement.MVC/Views/Login/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Rendering
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using LoginViewModel = UserManagement.MVC.Models.LoginViewModel

@model LoginViewModel

@{
    ViewBag.Title = "Login Page";
}

<div class="container mt-5 px-2">
    <form asp-action="Index" asp-controller="Login">
        <div>
            <span class="error-mes">@Html.ValidationMessage("NonexistentUser")</span>
            <span class="error-mes">@Html.ValidationMessage("IncorrectPassword")</span>
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-default">Email</span>
            </div>
            <input input asp-for="Email" type="text" id="email" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default">
            <span class="error-mes" asp-validation-for="Email"></span>
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-default">Password</span>
            </div>
            <input input asp-for="Password" type="password" id="password" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default">
            <span class="error-mes" asp-validation-for="Password"></span>
        </div>
        <div>
            <button type="submit" class="btn btn-outline-primary">Log on</button>
        </div>
    </form>
</div>


UserManagement.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="AdminPanel" asp-action="Index">Admin panel</a>
            <a class="navbar-brand" asp-area="" asp-controller="Registration" asp-action="Index">Registration</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            @if (User.Identity.IsAuthenticated)
            {
                <a asp-action="SignOut" asp-controller="AdminPanel" class="navbar-brand">Sign out</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            }     
            
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>